PhonBook/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using PhonBook.Core.Domain.Contacts;
using PhonBook.Core.Domain.Grops;
using PhonBook.Models;

namespace PhonBook.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactRepository _ContactRepository;
        private IGroupRepository _GroupRepository;
       

        public ContactController(IContactRepository contactRepository, IGroupRepository groupRepository)
        {
            _ContactRepository = contactRepository;
            _GroupRepository = groupRepository;
            
        }
        /// <summary>
        /// Create a new Contact object
        /// </summary>
        [HttpPost]
        public  async Task< ActionResult> Add_Contact (Vmcontact model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest("invalid contact");
                }
                var gruop = _GroupRepository.FindById(model.gropid);
                var new_contact = new Contact()
                {
                    Email = model.Email,
                    Fullname = model.Fullname,
                    Phone_number1 = model.Phone_number1,
                    Phone_number2 = model.Phone_number2,
                    POST = model.POST,
                    Tell_phone = model.Tell_phone,
                    Group_Id=0,
                };
                if (gruop!=null){
                    new_contact.Group_Id = model.gropid;
                }
                await _ContactRepository.Add(new_contact);
                return RedirectToAction("index", "Home");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);

            }
        }

        /// <summary>
        /// Deletes the specified contact
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            try
            {
                var contecat = await _ContactRepository.FindByIdAsync(Id);
                if (contecat == null)
                    return NotFound($"Message :{Id} not found" );
                _ContactRepository.Delete(Id);
                return RedirectToAction("index", "Home");
                // return RedirectToAction("Index", "Home");
            }
            catch (System.Exception ex)
            {
                return StatusCode(500,ex.Message);
            }
        }

        /// <summary>
        /// Updates the contact
        /// </summary>
        [HttpPost]
        public async Task< IActionResult> Update(Vmcontact model)
        {
            if (!ModelState.IsValid )
            {
                ViewBag.message = " Contact is  Not invalid";
                return BadRequest(model);
            }
            var Contact=await _ContactRepository.FindByIdAsync(model.Id);
            if (Contact==null){
                ViewBag.message = " Contact is  Not Found";
                return NotFound(model);
            }
            try
            {
                
                var editconact = new Contact()
                {
                    Email = model.Email,
                    Fullname = model.Fullname,
                    POST = model.POST,
                    Phone_number1 = model.Phone_number1,
                    Phone_number2 = model.Phone_number2,
                    Tell_phone = model.Tell_phone,
                    Group_Id = model.gropid,
                    Id=model.Id,
                    
                };
                var grop= await _GroupRepository.FindByNameAsync(model.Name_Grop);
                if(grop!=null){
                    editconact.Group_Id=grop.Id;
                }
                _ContactRepository.Update(model.Id, editconact);
                return RedirectToAction("index", "Home");
            }
            catch (System.Exception ex)
            {
                return StatusCode(500,ex.Message);
            }
        }
        /// <summary>
        /// get the contact
        /// </summary>
        [HttpGet]
        public JsonResult Find_Contact(int id)
        {
            var contact = _ContactRepository.FindById(id);
            return Json(contact);
        }
    }
}

PhonBook/Controllers/GropController.cs
using Microsoft.AspNetCore.Mvc;
using PhonBook.Core.Domain.Contacts;
using PhonBook.Core.Domain.Grops;
using PhonBook.infra.Data.sqlserver.Contacts;
using PhonBook.Models;
using System.Text.RegularExpressions;

namespace PhonBook.Controllers
{
    public class GropController : Controller
    {
        private readonly IGroupRepository _GroupRepository;
        private readonly IContactRepository _ContactRepository;
        private ILogger<GropController> _logger;

        public GropController(ILogger<GropController> logger, IGroupRepository groupRepository, IContactRepository contactRepository)
        {
            _GroupRepository = groupRepository;
            _ContactRepository = contactRepository;
            _logger=logger;
        }
        /// <summary>
        /// Create a New Grop
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Create(VmGrop model)
        {

            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(model);
                }
                var Grup = new Grop
                {
                    Address = model.Address,
                    Code_posti = model.Code_posti,
                    //Contacts = model.Contacts,
                    Fax = model.Fax,
                    Name = model.Name,
                    Name_Company = model.Name_Company,
                    Organization = model.Organization,
                    Tell_phone = model.Tell_phone,


                };
                await _GroupRepository.Add(Grup);
                return RedirectToAction("Index", "Home",new {Status="Lis_Group"});
            }
            catch (Exception ex)
            {
                //log error
                return StatusCode(500, ex.Message);
            }
        }
        /// <summary>
        /// Get a Grop
        /// </summary>
        [HttpGet]
        public JsonResult Get_Group(int id)
        {
            var result =  _GroupRepository.FindById(id);
            return Json(result);
        }
        /// <summary>
        /// Delete a group
        /// </summary>
        /// GET: /groups
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {  
            try
            {
               var grop = await _GroupRepository.FindByIdAsync(id);
                if (grop == null)
                    return NotFound();
                var contacts = await _ContactRepository.GetAllAsync();
                // foreach (var Contactedit in contacts)
                // {
                //     var conatct_edit = Contactedit;
                //     conatct_edit.Group_Id = 0;
                //     _ContactRepository.Update(Contactedit.Id, conatct_edit);
                // }
               var res= await _GroupRepository.DeleteAsync(id);
                _logger.LogInformation($"deleted grop result query: {res}");
                return RedirectToAction("Index", "Home",new {Status="Lis_Group"});
            }
            catch (Exception ex)
            {
                //log error
                return StatusCode(500, ex.Message);
            }

        }

        /// <summary>
        /// Edit a Grop
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Edit(VmGrop model)
        {
            try
            {
                var res = await _GroupRepository.FindByIdAsync(model.id);
                if (res == null)
                {
                    ViewBag.message = " group is  Not Found";
                    return BadRequest(ViewBag.message);
                }
                if (!ModelState.IsValid)
                {
                    ViewBag.message = " group is  Not invalid";
                    return BadRequest(model);
                }
                var EditGroup = new Grop
                {
                    Address = model.Address,
                    Code_posti = model.Code_posti,
                    Fax = model.Fax,
                    Name = model.Name,
                    Name_Company = model.Name_Company,
                    Organization = model.Organization,
                    Tell_phone = model.Tell_phone,
                };
                 var query = await _GroupRepository.Update(model.id, EditGroup);
                _logger.LogInformation($"update grop result{query}");
                return RedirectToAction("index", "Home",new {Status="Lis_Group"});
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [HttpGet]
        public JsonResult Find_members(int id_grop){
            try
            {
                var List_Coantact=_ContactRepository.GetAll();
                var res=List_Coantact.Any(c=>c.Group_Id==id_grop);
                return Json(res);
            }
            catch (System.Exception ex)
            {
                return Json(StatusCode(500,ex.Message));
            }
        }
    }
}

PhonBook/Views/Shared/_ContactsSummery.cshtml
@model Basemodel
@section pre
{
}
   <div class="row mt-2 mb-2 mx-1">
        @if (ViewBag.message != null)
        {
            <div class="row">
                <div class="alert alert-danger col-12">
                    @ViewBag.message
                </div>
            </div>
        }
    </div>
 <div class="col-lg-4 col-md-12 mx-0 mx-sm-2">
        <form asp-controller="Home" asp-action="Search_Contact"
            class="form-inline my-2 my-lg-0 mx-lg-0 d-flex  mx-0 responsive " method="get">
            <input name="Fullname" class="form-control " type="search" placeholder="نام و نام خانوادگی"
                aria-label="Search">
            <button class="btn btn-outline-light  mx-1" style="background-color: #FF3D00;" type="submit"> جستجو
            </button>
        </form>
    </div>
    <div class="col-lg-4 col-md-12 mx-0 mx-sm-2  ">

        <form asp-controller="Home" asp-action="Search_namegrop_Contact" class="form-inline my-2 my-lg-0 d-flex   responsive"
            method="get">
            <input name="Name_Grop" class="form-control" type="search" placeholder="جستجو مخاطب براساس نام گروه " aria-label="Search">
            <button class="btn  mx-1 btn-outline-light" style="background-color:#FF3D00;" type="submit">جستجو
            </button>
        </form>
    </div>
<section class="container-fluid">
    <div class="row mt-2">
        <div class="container table-responsive-lg">
            <table class="table  table-hover table-responsive-lg">
                <thead class=" text-center text-light " style="background-color: #8E24AA;">
                    <tr class="responsive ">
                        <th>ردیف</th>
                        <th>نام و نام خانوادگی</th>
                        <th>سمت </th>
                        <th>شماره ثابت</th>
                        <th>تلفن همراه</th>
                        <th>ایمیل</th>
                        <th>گروه</th>
                        <th> </th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody class="table-responsive">
                    @if (Model.Vmcontacts.Any())
                    {
                        int count = 1;
                        @foreach (var item in Model.Vmcontacts)
                        {
                            <tr class="responsive">
                                <td>@count</td>
                                <td>@item.Fullname</td>
                                <td>@item.POST</td>
                                <td>@item.Tell_phone</td>
                                <td>@item.Phone_number1</td>
                                <td>@item.Email</td>
                                <td>@item.Name_Grop</td>
                                <td hidden>@item.Id</td>
                                <td hidden>@item.gropid</td>
                                <td>
                                    <button class="btn btn-outline-light  btnn" style="background-color: #FFAB00;" value="@item.Id" data-toggle="modal" data-target="#editContact" >
                                        ویرایش
                                    </button>
                                </td>
                                <td>
                                    <button  style="background-color: #B71C1C;"  class="btn btn-outline-light deletebtn" value="@item.Id">
                                            حذف
                                    </button>
                                </td>
                            </tr>
                            count++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td class="alert-danger">
                                اطلاعاتی وجود ندارد
                            </td>
                        </tr>
                    }
                <tbody>
            </table>
        </div>
    </div>
</section>
<!-- Modal edit -->
<div id="editContact" class="modal fade" itabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">ویرایش اطلاعات  </h5>
                <button type="button" class="close btn-close-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <partial name="_EditContact"   />

            </div>
        </div>
    </div>
</div>
@section Scripts{
 
}

PhonBook/Views/Shared/_EditContact.cshtml
@model Basemodel
<input hidden id="gropnamecontact" value="@Model.vmcontact.gropid"/>
<div class="row m-0">
    <form class="form-control" asp-controller="Contact" asp-action="Update"  method="post">
        <div class="row">
            <div class="col-lg-6 col-lg-offset-2 mb-3">
                <label class="control-label required"> نام و نام خانوداگی </label>
                <input type="text" id="Fullname" name="Fullname" class="form-control border-secondary " required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')" data-validation="name" > 
                <span class="text-danger"></span>
                <div id="nameAlert"></div>
            </div>
            <div class="col-lg-6 col-lg-offset-2 mb-3">
                <label class="control-label required"> سمت </label>
                <input type="text" name="POST" id="post" class="form-control border-secondary "  required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')" />
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-lg-offset-2 mb-3">
                <label class="control-label required"> شماره ثابت </label>
                <input type="tel"  name="Tell_phone" id="Tell_phone"   maxlength="8" dir="ltr"  class="form-control border-secondary "  required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')"
                onkeypress="return onlyNumberKey(event)" />
                <span class="text-danger"></span>
            </div>
            <div class="col-lg-6 col-lg-offset-2 mb-3">
                <label class="control-label"> تلفن همراه </label>
                <input type="tel" name="Phone_number1" id="Phone_number1" class="form-control  border-secondary"  onkeypress="return onlyNumberKey(event)"
                    dir="ltr" maxlength="11">
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-lg-offset-2 mb-3">
                <label class="control-label"> ایمیل </label>
                <input type="email" name="Email" id="Email"  data-validation="" class="form-control border-secondary" id="email" >
            </div>
            <div class="col-lg-6 col-lg-offset-2 mb-3 ">
                <label class="control-label"> نام گروه </label>
                <select class="form-control  border-secondary" id="ddlIncidents_editmodal">
                    @if (Model.vmcontact.Name_Grop!=null)
                    {
                        <option class="selceltitem" selected id="modal_grop"> @Model.vmcontact.Name_Grop </option>
                    }
                    else{
                        <option class="selceltitem" selected id="modal_grop"> انتخاب گروه</option>
                    }
                    @foreach (var item in Model.Groups)
                    {
                        <option id="@item.Id" value="@item.Id"> @item.Name</option>
                    }
                </select>
                <input  hidden id="idgp" name="gropid" />
                <input  hidden id="IdContact" name="Id" />
                <input  hidden id="namegrop" name="Name_Grop" />
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-lg-3 col-lg-offset-2 mb-3">
                <label class="control-label"> نام گروه </label>
                <input type="text" class="form-control" disabled="disabled" id="namegap_editmodal" name="Name_Grop" placeholder=" ">
            </div>
            <div class="col-lg-3 col-lg-offset-2 mb-3">
                <label class="control-label"> نام شرکت </label>
                <input type="text" class="form-control" id="namecompony_editmodal" disabled="disabled" placeholder="">
            </div>
            <div class="col-lg-3 col-lg-offset-2 mb-3">
                <label class="control-label"> سازمان </label>
                <input type="text" disabled="disabled" class="form-control" id="nameorginzation_editmodal">
            </div>
            <div class="col-lg-3 col-lg-offset-2 mb-3">
                <label class="control-label"> تلفن </label>
                <input type="text" disabled="disabled" class="form-control " id="telephon_editmodal" >
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-lg-3 col-lg-offset-2 mb-3">
                <label class="control-label"> آدرس </label>
                <input type="text" disabled="disabled" class="form-control" id="addres_editmodal" placeholder="">
            </div>
            <div class="col-lg-3 col-lg-offset-2 mb-3">
                <label class="control-label"> کد پستی </label>
                <input type="text" disabled="disabled" class="form-control" id="codeposti_editmodal" placeholder="" onkeypress="return onlyNumberKey(event)">
            </div>
            <div class="col-lg-3 col-lg-offset-2 mb-3">
                <label class="control-label"> فکس </label>
                <input type="text" disabled="disabled" class="form-control" id="fax_editmodal" placeholder=" " onkeypress="return onlyNumberKey(event)">
            </div>
        </div>
        <div class="row">
            <button type="submit" class="btn btn-success">ذخیره</button>
        </div>
    </form>
</div>

@section Scripts{

}

PhonBook/Views/Shared/_EditGrop.cshtml
@model Basemodel
@section pre{

}
<div class="container">
    <form class="form-control" asp-controller="Grop" asp-action="Edit" method="post">
        <input name="id" id="Idgropedit"  hidden />
        <div class="col-form-label border-1">
            افزودن گروه:
        </div>
        <div class="row mb-3">
            <div class="col-lg-6 ">
                <label class="control-label required"> نام گروه : </label>
                <input type="text"   name="Name" id="namegrop_modaledit" class="form-control  border-secondary" required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')">
                <span class="text-danger"></span>
            </div>
            <div class="col-lg-6">
                <label class="control-label required"> نام شرکت : </label> 
                <input type="text"   name="Name_Company" id="Name_Company_modaledit" required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')"
                    class="form-control  border-secondary" >
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-lg-6">
                <label class="control-label required"> سازمان : </label>
                <input type="text"  name="Organization" id="Organization_modaledit"
                    class="form-control  border-secondary" required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')">
                <span class="text-danger"></span>
            </div>
            <div class="col-lg-6">
                <label class="control-label required"> تلفن : </label>
                <input type="tel"  name="Tell_phone" id="Tell_phone_modaledit" class="form-control  border-secondary" onkeypress="return onlyNumberKey(event)"
                    data-validation="number"  id="name" placeholder=" 3145552001 " dir="ltr" value="31" maxlength="8" required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')">
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-lg-6">
                <label class="control-label required"> آدرس : </label>
                <input type="text"  name="Address" id="Address_modaledit" class="form-control  border-secondary"
                    required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')">
                <span class="text-danger"></span>
            </div>
            <div class="col-lg-6">
                <label class="control-label required"> کد پستی : </label>
                <input type="tel"  name="Code_posti" id="Code_posti_modaledit" class="form-control  border-secondary" onkeypress="return onlyNumberKey(event)"
                    data-validation="number" required dir="ltr" maxlength="10" placeholder="8178188718" required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')">
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-lg-6">
                <label class="control-label siz required" > فکس:</label>
                <input type="tel"  name="Fax" id="Fax_modaledit" class="form-control  border-secondary" onkeypress="return onlyNumberKey(event)"
                    data-validation-allowing="number" required maxlength="8" dir="ltr" placeholder="" required oninvalid="this.setCustomValidity('این فیلد نمیتواند خالی باشد ')" oninput="setCustomValidity('')">
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-success">ذخیره</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
        </div>
    </form>
</div>
@section Scripts{
}

PhonBook/Views/Shared/_GropsSummery.cshtml
@model Basemodel
   <div class="col-lg-4 col-md-12 mx-0 mx-sm-2  ">

        <form asp-controller="Home" asp-action="Search_Group" class="form-inline my-2 my-lg-0 d-flex   responsive"
            method="get">
            <input name="Name_Grop" class="form-control" type="search" placeholder="جستجو  گروه " aria-label="Search">
            <button class="btn  mx-1 btn-outline-light" style="background-color:#FF3D00;" type="submit">جستجو
            </button>
        </form>
    </div>
<div class="row">

    <div class="container p-3">

        <div class="container-fluid ">
            <div class="container table-responsive-lg">
                <table class="table  table-hover table-responsive-lg ">
                    <thead class="text-light  " style="background-color: #8E24AA;">
                        <tr>
                            <th>ردیف</th>
                            <th>نام گروه</th>
                            <th>نام سازمان</th>
                            <th>تلفن </th>
                            <th>آدرس</th>
                            <th> </th>
                            <th> </th>

                        </tr>
                    </thead>
                    <tbody class="table-responsive">
                        @if (Model.VmGrops.Any())
                        {
                            int count = 1;
                            @foreach (var item in Model.VmGrops)
                            {
                                <tr>
                                    <td>@count</td>
                                    <td>@item.Name</td>
                                    <td>@item.Organization</td>
                                    <td>@item.Tell_phone</td>
                                    <td>@item.Address</td>
                                    <td hidden>@item.Code_posti</td>
                                    <td hidden>@item.Name_Company</td>
                                    <td hidden>@item.Fax</td>
                                    <td hidden>@item.id</td>
                                    <td>
                                        <button value="@item.id" class="btn  btn-outline-light editgrop" style="background-color: #FFAB00;" 
                                            data-toggle="modal" data-target="#editgrop">
                                            ویرایش
                                        </button>
                                    </td>
                                    <td>
                                        <button  value="@item.id" style="background-color: #B71C1C;" class="btn btn-outline-light btngropdelet">
                                            حذف
                                        </button>
                                    </td>
                                </tr>
                                count++;
                            }
                        }
                        else
                        {
                            <tr>

                                <td>
                                    <div class="border-warning">
                                        اطلاعاتی وجود ندارد
                                    </div>
                                </td>
                            </tr>
                        }
                    <tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="editgrop" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"> فرم ویرایش </h5>
                <button type="button" class="btn-close-white" data-dismiss="modal" dir="" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="row">
                <partial name="_EditGrop" />
            </div>
        </div>
    </div>
</div>
@section Scripts{
<script>
    $(".btngropdelet").click(function(){
        var idgrop=$(this).val();
        var result;
        $.ajax({
            type: "GET",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            url: "@Url.Action("Find_members", "Grop")",
                    data: { 'id': idgrop },
                    success: (response)=> {
                        result.response;
                        console.log(response);
                    },
                    failure: function (response) {
                        alert("response:" + response.responseText);
                        },
                    error: function (response) {
                        alert("response:" + response.responseText);
                    }
        })
    });
</script>
}